### ISSUE TITLE
Proposal / Setup a docker version

### ISSUE THREAD

**Issue by pascalandy** [ageitgey/medium_to_ghost#1]
Hi,

I would like to help to create the docker version of it. As I don't have a medium blog, I have a question, do you have Medium export I could work with? If you don't I will create a dummy user then :)

Cheers!

**Comment by pascalandy** [comment]
Don't be shy to remind me if I don't give you feedback :) Your project is too cool!

**Comment by ageitgey** [comment]
Thanks! I tried to create a dummy user, but Medium makes you tie your account to a real Facebook or Google login so I wasn't able to make a second account. So unfortunately I don't have a sample export to share. But feel free to set up a docker version!

**Comment by pascalandy** [comment]
OK, I'll do it then. See ya!
