### ISSUE TITLE
Can't launch at MacOS 10.14.

### ISSUE THREAD

**Issue by Olexiy665** [ageitgey/medium_to_ghost#5]
if I launch as in README - then receive 
`/Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'medium_to_ghost.py': [Errno 2] No such file or directory`

If I clone project and navigate to folder and run as `python3 ./medium_to_ghost/medium_to_ghost.py  /path-to.zip` then receive:

`Traceback (most recent call last):
  File "./medium_to_ghost/medium_to_ghost.py", line 3, in <module>
    from medium_to_ghost.medium_post_parser import convert_medium_post_to_ghost_json
  File "/Users/oleksiikryvonosov/upblog/medium_to_ghost/medium_to_ghost/medium_to_ghost.py", line 3, in <module>
    from medium_to_ghost.medium_post_parser import convert_medium_post_to_ghost_json
`

**Comment by monorkin** [comment]
I experienced the exact same issue just now, but discovered by accident that I had a new file in my `bin` directory named `medium_to_ghost`. I tried the following and it worked for me:

```bash
chmod +x /usr/local/bin/medium_to_ghost
/usr/local/bin/medium_to_ghost ./medium-export.zip
```

Hope this helps.

**Comment by ferdi2005** [comment]
Thanks @monorkin , it worked very well! @ageitgey Please add that to the instructions
