### ISSUE TITLE
Escape white title post

### ISSUE THREAD

**Issue by ferdi2005** [ageitgey/medium_to_ghost#6]
I have had on my export 7 posts with no title. I think it's a good idea to ignore them when generating the JSON because they block import on Ghost.

**Comment by paramaggarwal** [comment]
This is an excellent script, and worked well. We can add a dummy title if title is not found.

<img width="660" alt="Screenshot 2019-05-25 at 10 24 49 AM" src="https://user-images.githubusercontent.com/543981/58364806-71926a00-7ed7-11e9-8a6e-d2aa9e2ee369.png">

**Comment by ageitgey** [comment]
Fixed by #8
