### ISSUE TITLE
Ghost Now Includes Custom Canonical URLs

### ISSUE THREAD

**Issue by slavakurilyak** [ageitgey/medium_to_ghost#7]
On March 19, 2019, Ghost released [custom canonical URLs](https://blog.ghost.org/custom-canonical-urls/). This `medium_to_ghost` library can finally resolve SEO issues during the importation process from Medium to Ghost.

![--Link-rel-canonical-feature-img](https://user-images.githubusercontent.com/6625584/54886801-4644bd80-4e49-11e9-8ee1-20f67074dd16.jpg)

**Comment by ageitgey** [comment]
That's awesome! Thanks for letting me know. I'll see if I can add that real quick.

**Comment by ageitgey** [comment]
Added in v0.3. Now the canonical url is set for each imported post.
