### ISSUE TITLE
urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] 

### ISSUE THREAD

**Issue by brunobuddy** [ageitgey/medium_to_ghost#9]
I am getting an error because of some failed validation when I follow the README 
```
self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
```

This happends when I do ` python3 -m medium_to_ghost.medium_to_ghost medium-export.zip`on MacOS 10.14.4 and using Python 3.7.3

**Comment by polluterofminds** [comment]
Running this command seems to work: 

`sudo /Applications/Python\ 3.7/Install\ Certificates.command`

Make sure to specify the correct version of Python installed on your machine. This command also assumes you're using MacOS.

**Comment by ageitgey** [comment]
The response from @jehunter5811 is correct. The problem is that Python on Mac doesn't install SSL certificates by default for some reason and you have to run that command manually to install them. Otherwise no python programs can access https sites.
